### ISSUE TITLE
Match version of docker image with the version of the binary

### ISSUE THREAD

**Issue by itskingori** [Intellection/docker-oauth2-proxy#5]
I think we should a versioning system that matches the version of the `oauth2_proxy` binary. Changes to the building and other unrelated files don't really change the version that we run.

**Comment by itskingori** [comment]
@zacblazic Have a look at the releases here: https://github.com/bitly/oauth2_proxy/releases.

**Comment by itskingori** [comment]
@zacblazic This idea is also coming from the realisation that most Docker images that we use follow the version (to some extent) the version number of the software that they are trying to package.

**Comment by zacblazic** [comment]
I agree with this, never actually though to do it though. It makes sense.

**Comment by itskingori** [comment]
Yeah, in this case I think it makes more sense because we are trying to package a binary as an image for re-use. It makes sense to stick to `image_name:x.y` for that you just pick the container version with the binary version you want (since they match).
